/**
 * KAGE MCP Server Registry
 * 50+ app integrations via Model Context Protocol
 *
 * Categories: Development, Productivity, Communication, Data, Cloud, AI/ML, Finance, Design, Security, Other
 */

import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));

export const MCP_CATEGORIES = {
  development: { id: 'development', name: 'Development', icon: '💻', nameJa: '開発' },
  productivity: { id: 'productivity', name: 'Productivity', icon: '📋', nameJa: '生産性' },
  communication: { id: 'communication', name: 'Communication', icon: '💬', nameJa: 'コミュニケーション' },
  data: { id: 'data', name: 'Data & Storage', icon: '🗄️', nameJa: 'データ' },
  cloud: { id: 'cloud', name: 'Cloud & DevOps', icon: '☁️', nameJa: 'クラウド' },
  ai: { id: 'ai', name: 'AI & ML', icon: '🤖', nameJa: 'AI・ML' },
  search: { id: 'search', name: 'Search & Web', icon: '🔍', nameJa: '検索・Web' },
  finance: { id: 'finance', name: 'Finance', icon: '💰', nameJa: '金融' },
  design: { id: 'design', name: 'Design', icon: '🎨', nameJa: 'デザイン' },
  desktop: { id: 'desktop', name: 'Desktop & Office', icon: '🖥️', nameJa: 'デスクトップ' },
  other: { id: 'other', name: 'Other', icon: '📦', nameJa: 'その他' },
};

export const BUILTIN_MCP_SERVERS = [
  // ─────────────────── Development ───────────────────
  {
    id: 'filesystem',
    name: 'Filesystem',
    description: 'Local file system read/write access',
    category: 'development',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', process.env.HOME || '/tmp'],
    permissions: ['read', 'write'],
    default_enabled: true,
    envKeys: [],
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Repos, issues, PRs, actions, code search',
    category: 'development',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    env: { GITHUB_PERSONAL_ACCESS_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write', 'admin'],
    default_enabled: false,
    envKeys: ['GITHUB_PERSONAL_ACCESS_TOKEN'],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'GitLab repos, MRs, pipelines, issues',
    category: 'development',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-gitlab'],
    env: { GITLAB_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['GITLAB_TOKEN'],
  },
  {
    id: 'git',
    name: 'Git',
    description: 'Local Git repository operations',
    category: 'development',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-git'],
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'docker',
    name: 'Docker',
    description: 'Container management, images, volumes',
    category: 'development',
    command: 'npx',
    args: ['-y', 'mcp-server-docker'],
    permissions: ['read', 'write', 'admin'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'npm',
    name: 'npm',
    description: 'Package search, info, version tracking',
    category: 'development',
    command: 'npx',
    args: ['-y', 'mcp-server-npm'],
    permissions: ['read'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Error tracking, performance monitoring',
    category: 'development',
    command: 'npx',
    args: ['-y', '@sentry/mcp-server'],
    env: { SENTRY_AUTH_TOKEN: '{{user_config}}' },
    permissions: ['read'],
    default_enabled: false,
    envKeys: ['SENTRY_AUTH_TOKEN'],
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Issue tracking, project management',
    category: 'development',
    command: 'npx',
    args: ['-y', '@linear/mcp-server'],
    env: { LINEAR_API_KEY: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['LINEAR_API_KEY'],
  },
  {
    id: 'playwright',
    name: 'Playwright',
    description: 'Browser automation and testing',
    category: 'development',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-playwright'],
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer',
    description: 'Headless Chrome automation',
    category: 'development',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-puppeteer'],
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: [],
  },

  // ─────────────────── Productivity ───────────────────
  {
    id: 'google_workspace',
    name: 'Google Workspace',
    description: 'Gmail, Drive, Calendar, Docs, Sheets',
    category: 'productivity',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-google-workspace'],
    permissions: ['gmail:read', 'gmail:write', 'calendar:read', 'calendar:write', 'drive:read'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'google_drive',
    name: 'Google Drive',
    description: 'File management, search, sharing',
    category: 'productivity',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-gdrive'],
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Pages, databases, blocks, search',
    category: 'productivity',
    command: 'npx',
    args: ['-y', '@notionhq/mcp-server'],
    env: { NOTION_API_KEY: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['NOTION_API_KEY'],
  },
  {
    id: 'todoist',
    name: 'Todoist',
    description: 'Task management, projects, labels',
    category: 'productivity',
    command: 'npx',
    args: ['-y', 'mcp-server-todoist'],
    env: { TODOIST_API_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['TODOIST_API_TOKEN'],
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Project and task management',
    category: 'productivity',
    command: 'npx',
    args: ['-y', 'mcp-server-asana'],
    env: { ASANA_ACCESS_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['ASANA_ACCESS_TOKEN'],
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Issues, sprints, boards, JQL search',
    category: 'productivity',
    command: 'npx',
    args: ['-y', 'mcp-server-jira'],
    env: { JIRA_URL: '{{user_config}}', JIRA_EMAIL: '{{user_config}}', JIRA_API_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['JIRA_URL', 'JIRA_EMAIL', 'JIRA_API_TOKEN'],
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Boards, lists, cards management',
    category: 'productivity',
    command: 'npx',
    args: ['-y', 'mcp-server-trello'],
    env: { TRELLO_API_KEY: '{{user_config}}', TRELLO_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['TRELLO_API_KEY', 'TRELLO_TOKEN'],
  },
  {
    id: 'confluence',
    name: 'Confluence',
    description: 'Wiki pages, spaces, search',
    category: 'productivity',
    command: 'npx',
    args: ['-y', 'mcp-server-confluence'],
    env: { CONFLUENCE_URL: '{{user_config}}', CONFLUENCE_EMAIL: '{{user_config}}', CONFLUENCE_API_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['CONFLUENCE_URL', 'CONFLUENCE_EMAIL', 'CONFLUENCE_API_TOKEN'],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Bases, tables, records management',
    category: 'productivity',
    command: 'npx',
    args: ['-y', 'mcp-server-airtable'],
    env: { AIRTABLE_API_KEY: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['AIRTABLE_API_KEY'],
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Vault notes, search, linking',
    category: 'productivity',
    command: 'npx',
    args: ['-y', 'mcp-server-obsidian'],
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'apple_notes',
    name: 'Apple Notes',
    description: 'macOS Notes app integration',
    category: 'productivity',
    command: 'npx',
    args: ['-y', 'mcp-server-apple-notes'],
    permissions: ['read'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'evernote',
    name: 'Evernote',
    description: 'Notes, notebooks, tags, search',
    category: 'productivity',
    command: 'npx',
    args: ['-y', 'mcp-server-evernote'],
    env: { EVERNOTE_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['EVERNOTE_TOKEN'],
  },

  // ─────────────────── Communication ───────────────────
  {
    id: 'slack',
    name: 'Slack',
    description: 'Messages, channels, users, search',
    category: 'communication',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-slack'],
    env: { SLACK_BOT_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['SLACK_BOT_TOKEN'],
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Servers, channels, messages',
    category: 'communication',
    command: 'npx',
    args: ['-y', 'mcp-server-discord'],
    env: { DISCORD_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['DISCORD_TOKEN'],
  },
  {
    id: 'microsoft_teams',
    name: 'Microsoft Teams',
    description: 'Teams, chats, channels, meetings',
    category: 'communication',
    command: 'npx',
    args: ['-y', 'mcp-server-teams'],
    env: { TEAMS_ACCESS_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['TEAMS_ACCESS_TOKEN'],
  },
  {
    id: 'email',
    name: 'Email (IMAP/SMTP)',
    description: 'Generic email send/receive via IMAP/SMTP',
    category: 'communication',
    command: 'npx',
    args: ['-y', 'mcp-server-email'],
    env: { EMAIL_HOST: '{{user_config}}', EMAIL_USER: '{{user_config}}', EMAIL_PASS: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['EMAIL_HOST', 'EMAIL_USER', 'EMAIL_PASS'],
  },
  {
    id: 'telegram',
    name: 'Telegram',
    description: 'Bot messaging, groups, channels',
    category: 'communication',
    command: 'npx',
    args: ['-y', 'mcp-server-telegram'],
    env: { TELEGRAM_BOT_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['TELEGRAM_BOT_TOKEN'],
  },

  // ─────────────────── Data & Storage ───────────────────
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Query, schema inspection, data management',
    category: 'data',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres'],
    env: { POSTGRES_URL: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['POSTGRES_URL'],
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: 'Query, schema, data operations',
    category: 'data',
    command: 'npx',
    args: ['-y', 'mcp-server-mysql'],
    env: { MYSQL_URL: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['MYSQL_URL'],
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    description: 'Local SQLite database access',
    category: 'data',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sqlite'],
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    description: 'Document queries, collections, aggregation',
    category: 'data',
    command: 'npx',
    args: ['-y', 'mcp-server-mongodb'],
    env: { MONGODB_URI: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['MONGODB_URI'],
  },
  {
    id: 'redis',
    name: 'Redis',
    description: 'Key-value operations, pub/sub',
    category: 'data',
    command: 'npx',
    args: ['-y', 'mcp-server-redis'],
    env: { REDIS_URL: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['REDIS_URL'],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Database, auth, storage, edge functions',
    category: 'data',
    command: 'npx',
    args: ['-y', 'mcp-server-supabase'],
    env: { SUPABASE_URL: '{{user_config}}', SUPABASE_KEY: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['SUPABASE_URL', 'SUPABASE_KEY'],
  },
  {
    id: 'firebase',
    name: 'Firebase',
    description: 'Firestore, Auth, Storage, Functions',
    category: 'data',
    command: 'npx',
    args: ['-y', 'mcp-server-firebase'],
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    description: 'Vector database, embeddings, search',
    category: 'data',
    command: 'npx',
    args: ['-y', 'mcp-server-pinecone'],
    env: { PINECONE_API_KEY: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['PINECONE_API_KEY'],
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    description: 'Vector similarity search',
    category: 'data',
    command: 'npx',
    args: ['-y', 'mcp-server-qdrant'],
    env: { QDRANT_URL: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['QDRANT_URL'],
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    description: 'Data warehouse queries and management',
    category: 'data',
    command: 'npx',
    args: ['-y', 'mcp-server-snowflake'],
    env: { SNOWFLAKE_ACCOUNT: '{{user_config}}', SNOWFLAKE_USER: '{{user_config}}', SNOWFLAKE_PASSWORD: '{{user_config}}' },
    permissions: ['read'],
    default_enabled: false,
    envKeys: ['SNOWFLAKE_ACCOUNT', 'SNOWFLAKE_USER', 'SNOWFLAKE_PASSWORD'],
  },

  // ─────────────────── Cloud & DevOps ───────────────────
  {
    id: 'aws',
    name: 'AWS',
    description: 'S3, EC2, Lambda, CloudWatch, IAM',
    category: 'cloud',
    command: 'npx',
    args: ['-y', 'mcp-server-aws'],
    env: { AWS_ACCESS_KEY_ID: '{{user_config}}', AWS_SECRET_ACCESS_KEY: '{{user_config}}', AWS_REGION: '{{user_config}}' },
    permissions: ['read', 'write', 'admin'],
    default_enabled: false,
    envKeys: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_REGION'],
  },
  {
    id: 'gcp',
    name: 'Google Cloud',
    description: 'GCS, Compute, BigQuery, Cloud Functions',
    category: 'cloud',
    command: 'npx',
    args: ['-y', 'mcp-server-gcp'],
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'azure',
    name: 'Azure',
    description: 'Blob Storage, VMs, Functions, CosmosDB',
    category: 'cloud',
    command: 'npx',
    args: ['-y', 'mcp-server-azure'],
    env: { AZURE_SUBSCRIPTION_ID: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['AZURE_SUBSCRIPTION_ID'],
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Deployments, projects, domains, logs',
    category: 'cloud',
    command: 'npx',
    args: ['-y', 'mcp-server-vercel'],
    env: { VERCEL_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['VERCEL_TOKEN'],
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'Workers, Pages, DNS, KV, R2',
    category: 'cloud',
    command: 'npx',
    args: ['-y', '@cloudflare/mcp-server-cloudflare'],
    env: { CLOUDFLARE_API_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['CLOUDFLARE_API_TOKEN'],
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    description: 'Pods, deployments, services, logs',
    category: 'cloud',
    command: 'npx',
    args: ['-y', 'mcp-server-kubernetes'],
    permissions: ['read', 'write', 'admin'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'terraform',
    name: 'Terraform',
    description: 'Infrastructure as code, state management',
    category: 'cloud',
    command: 'npx',
    args: ['-y', 'mcp-server-terraform'],
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'netlify',
    name: 'Netlify',
    description: 'Sites, deploys, functions, forms',
    category: 'cloud',
    command: 'npx',
    args: ['-y', 'mcp-server-netlify'],
    env: { NETLIFY_AUTH_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['NETLIFY_AUTH_TOKEN'],
  },

  // ─────────────────── Search & Web ───────────────────
  {
    id: 'brave_search',
    name: 'Brave Search',
    description: 'Web search via Brave Search API',
    category: 'search',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    env: { BRAVE_API_KEY: '{{user_config}}' },
    permissions: ['search'],
    default_enabled: false,
    envKeys: ['BRAVE_API_KEY'],
  },
  {
    id: 'tavily',
    name: 'Tavily',
    description: 'AI-optimized web search and extraction',
    category: 'search',
    command: 'npx',
    args: ['-y', 'mcp-server-tavily'],
    env: { TAVILY_API_KEY: '{{user_config}}' },
    permissions: ['search'],
    default_enabled: false,
    envKeys: ['TAVILY_API_KEY'],
  },
  {
    id: 'fetch',
    name: 'Web Fetch',
    description: 'Fetch and extract content from URLs',
    category: 'search',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-fetch'],
    permissions: ['read'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    description: 'Web scraping, crawling, structured extraction',
    category: 'search',
    command: 'npx',
    args: ['-y', 'mcp-server-firecrawl'],
    env: { FIRECRAWL_API_KEY: '{{user_config}}' },
    permissions: ['read'],
    default_enabled: false,
    envKeys: ['FIRECRAWL_API_KEY'],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    description: 'Video search, transcripts, metadata',
    category: 'search',
    command: 'npx',
    args: ['-y', 'mcp-server-youtube'],
    env: { YOUTUBE_API_KEY: '{{user_config}}' },
    permissions: ['read'],
    default_enabled: false,
    envKeys: ['YOUTUBE_API_KEY'],
  },

  // ─────────────────── AI & ML ───────────────────
  {
    id: 'huggingface',
    name: 'Hugging Face',
    description: 'Models, datasets, spaces, inference',
    category: 'ai',
    command: 'npx',
    args: ['-y', 'mcp-server-huggingface'],
    env: { HF_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['HF_TOKEN'],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    description: 'ML model inference, image generation',
    category: 'ai',
    command: 'npx',
    args: ['-y', 'mcp-server-replicate'],
    env: { REPLICATE_API_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['REPLICATE_API_TOKEN'],
  },
  {
    id: 'langchain',
    name: 'LangChain / LangSmith',
    description: 'Traces, runs, datasets, evaluation',
    category: 'ai',
    command: 'npx',
    args: ['-y', 'mcp-server-langsmith'],
    env: { LANGSMITH_API_KEY: '{{user_config}}' },
    permissions: ['read'],
    default_enabled: false,
    envKeys: ['LANGSMITH_API_KEY'],
  },

  // ─────────────────── Finance ───────────────────
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payments, customers, subscriptions, invoices',
    category: 'finance',
    command: 'npx',
    args: ['-y', '@stripe/mcp-server'],
    env: { STRIPE_SECRET_KEY: '{{user_config}}' },
    permissions: ['read'],
    default_enabled: false,
    envKeys: ['STRIPE_SECRET_KEY'],
  },
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Products, orders, customers, inventory',
    category: 'finance',
    command: 'npx',
    args: ['-y', 'mcp-server-shopify'],
    env: { SHOPIFY_STORE_URL: '{{user_config}}', SHOPIFY_ACCESS_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['SHOPIFY_STORE_URL', 'SHOPIFY_ACCESS_TOKEN'],
  },

  // ─────────────────── Design ───────────────────
  {
    id: 'figma',
    name: 'Figma',
    description: 'Files, components, styles, comments',
    category: 'design',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-figma'],
    env: { FIGMA_ACCESS_TOKEN: '{{user_config}}' },
    permissions: ['read'],
    default_enabled: false,
    envKeys: ['FIGMA_ACCESS_TOKEN'],
  },

  // ─────────────────── Desktop & Office ───────────────────
  {
    id: 'local_apps',
    name: 'Local Apps',
    description: 'Launch and control local applications, read/write Excel/PowerPoint, AppleScript automation',
    category: 'desktop',
    command: 'node',
    args: [join(__dirname, 'servers/local-apps/index.js')],
    permissions: ['read', 'write', 'admin'],
    default_enabled: true,
    envKeys: [],
  },

  // ─────────────────── Other ───────────────────
  {
    id: 'time',
    name: 'Time',
    description: 'Current time, timezone conversion',
    category: 'other',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-time'],
    permissions: ['read'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'memory_mcp',
    name: 'Memory (Persistent)',
    description: 'Key-value persistent memory store',
    category: 'other',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'sequentialthinking',
    name: 'Sequential Thinking',
    description: 'Step-by-step reasoning and problem solving',
    category: 'other',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    permissions: ['read'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'shell',
    name: 'Shell',
    description: 'Execute shell commands with safety controls',
    category: 'other',
    command: 'npx',
    args: ['-y', 'mcp-server-shell'],
    permissions: ['read', 'write', 'admin'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'calendar',
    name: 'Calendar (CalDAV)',
    description: 'Calendar events via CalDAV protocol',
    category: 'other',
    command: 'npx',
    args: ['-y', 'mcp-server-calendar'],
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: [],
  },
  {
    id: 'weather',
    name: 'Weather',
    description: 'Current weather and forecasts',
    category: 'other',
    command: 'npx',
    args: ['-y', 'mcp-server-weather'],
    env: { OPENWEATHER_API_KEY: '{{user_config}}' },
    permissions: ['read'],
    default_enabled: false,
    envKeys: ['OPENWEATHER_API_KEY'],
  },
  {
    id: 'wolfram',
    name: 'Wolfram Alpha',
    description: 'Computational knowledge, math, data',
    category: 'other',
    command: 'npx',
    args: ['-y', 'mcp-server-wolfram'],
    env: { WOLFRAM_APP_ID: '{{user_config}}' },
    permissions: ['read'],
    default_enabled: false,
    envKeys: ['WOLFRAM_APP_ID'],
  },
  {
    id: 'twitter',
    name: 'Twitter / X',
    description: 'Posts, search, timeline, engagement',
    category: 'communication',
    command: 'npx',
    args: ['-y', 'mcp-server-twitter'],
    env: { TWITTER_BEARER_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['TWITTER_BEARER_TOKEN'],
  },
  {
    id: 'spotify',
    name: 'Spotify',
    description: 'Playlists, tracks, search, playback',
    category: 'other',
    command: 'npx',
    args: ['-y', 'mcp-server-spotify'],
    env: { SPOTIFY_CLIENT_ID: '{{user_config}}', SPOTIFY_CLIENT_SECRET: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['SPOTIFY_CLIENT_ID', 'SPOTIFY_CLIENT_SECRET'],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Trigger 7000+ app automations',
    category: 'other',
    command: 'npx',
    args: ['-y', 'mcp-server-zapier'],
    env: { ZAPIER_NLA_API_KEY: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['ZAPIER_NLA_API_KEY'],
  },
  {
    id: 'make',
    name: 'Make (Integromat)',
    description: 'Visual workflow automation',
    category: 'other',
    command: 'npx',
    args: ['-y', 'mcp-server-make'],
    env: { MAKE_API_TOKEN: '{{user_config}}' },
    permissions: ['read', 'write'],
    default_enabled: false,
    envKeys: ['MAKE_API_TOKEN'],
  },
];

/**
 * Get servers grouped by category
 */
export function getServersByCategory() {
  const grouped = {};
  for (const server of BUILTIN_MCP_SERVERS) {
    const cat = server.category || 'other';
    if (!grouped[cat]) {
      grouped[cat] = {
        ...MCP_CATEGORIES[cat],
        servers: [],
      };
    }
    grouped[cat].servers.push(server);
  }
  return grouped;
}
